/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        "tertiary-fixed": "#ffddb8",
        "on-error": "#ffffff",
        "primary-fixed": "#c4e7ff",
        "on-surface": "#171c20",
        "error": "#ba1a1a",
        "tertiary-fixed-dim": "#ffb960",
        "outline-variant": "#bdc8d1",
        "on-tertiary": "#ffffff",
        "primary-fixed-dim": "#7bd0ff",
        "on-primary-fixed": "#001e2c",
        "border-muted": "#E2E8F0",
        "surface-bright": "#f5faff",
        "surface-container-highest": "#dee3e8",
        "success-green": "#05AC5F",
        "secondary-container": "#dae2fd",
        "outline": "#6e7980",
        "inverse-primary": "#7bd0ff",
        "on-tertiary-container": "#613b00",
        "surface-variant": "#dee3e8",
        "on-secondary-fixed-variant": "#3f465c",
        "surface-dim": "#d6dbdf",
        "on-tertiary-fixed": "#2a1700",
        "surface-container-high": "#e4e9ee",
        "on-background": "#171c20",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed": "#dae2fd",
        "surface-subtle": "#F8FAFC",
        "on-secondary-container": "#5c647a",
        "tertiary": "#855300",
        "on-surface-variant": "#3e484f",
        "secondary": "#565e74",
        "inverse-surface": "#2c3135",
        "inverse-on-surface": "#edf1f6",
        "on-primary-fixed-variant": "#004c69",
        "on-tertiary-fixed-variant": "#653e00",
        "on-error-container": "#93000a",
        "tertiary-container": "#f1a02b",
        "surface-tint": "#00668a",
        "on-secondary": "#ffffff",
        "background": "#f5faff",
        "surface": "#f5faff",
        "surface-container": "#eaeef3",
        "primary": "#00668a",
        "primary-container": "#38bdf8",
        "on-primary": "#ffffff",
        "on-primary-container": "#004965",
        "surface-container-low": "#eff4f9",
        "secondary-fixed-dim": "#bec6e0",
        "error-container": "#ffdad6",
        "on-secondary-fixed": "#131b2e",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "container-max": "1280px",
        "margin-desktop": "2.5rem",
        "margin-mobile": "1rem",
        "section-gap": "5rem",
        "gutter": "1.5rem",
      },
      maxWidth: {
        "container-max": "1280px",
      },
      fontFamily: {
        "display-lg-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "display-lg": ["Plus Jakarta Sans", "sans-serif"],
      },
      fontSize: {
        "display-lg-mobile": ["32px", { lineHeight: "1.2", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "display-lg": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
}
